## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hobart,AU,-42.8794,147.3294,49.05,85,14,1.01,few clouds
1,1,Santa Luzia,BR,-19.7697,-43.8514,77.90,76,90,2.84,light rain
2,2,Bosaso,SO,11.2842,49.1816,75.63,72,1,4.70,clear sky
3,3,Almaznyy,RU,48.0448,40.0450,42.94,99,100,7.20,light rain
4,4,Vostok,RU,46.4856,135.8833,-11.20,99,100,4.27,overcast clouds

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [8]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Santa Luzia,BR,-19.7697,-43.8514,77.90,76,90,2.84,light rain
2,2,Bosaso,SO,11.2842,49.1816,75.63,72,1,4.70,clear sky
6,6,Butaritari,KI,3.0707,172.7902,80.02,80,54,11.41,moderate rain
7,7,Cidreira,BR,-30.1811,-50.2056,81.23,72,14,16.04,few clouds
10,10,Karratha,AU,-20.7377,116.8463,82.51,74,99,6.08,overcast clouds
20,20,Vila Velha,BR,-20.3297,-40.2925,77.95,87,75,9.22,broken clouds
26,26,Carnarvon,AU,-24.8667,113.6333,79.25,74,1,14.29,clear sky
28,28,Pitimbu,BR,-7.4706,-34.8086,84.79,64,97,11.03,overcast clouds
31,31,Sao Joao Da Barra,BR,-21.6403,-41.0511,80.69,88,95,11.50,overcast clouds
36,36,San Isidro,PE,-12.1167,-77.0500,76.59,67,0,4.00,clear sky

In [9]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                201
City                   201
Country                199
Lat                    201
Lng                    201
Max Temp               201
Humidity               201
Cloudiness             201
Wind Speed             201
Current Description    201
dtype: int64

In [18]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
1,1,Santa Luzia,BR,-19.7697,-43.8514,77.90,76,90,2.84,light rain
2,2,Bosaso,SO,11.2842,49.1816,75.63,72,1,4.70,clear sky
6,6,Butaritari,KI,3.0707,172.7902,80.02,80,54,11.41,moderate rain
7,7,Cidreira,BR,-30.1811,-50.2056,81.23,72,14,16.04,few clouds
10,10,Karratha,AU,-20.7377,116.8463,82.51,74,99,6.08,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
653,653,Amarante Do Maranhao,BR,-5.5667,-46.7422,85.93,60,100,6.96,overcast clouds
654,654,Araguaina,BR,-7.1911,-48.2072,83.61,70,51,1.25,broken clouds
658,658,Boyolangu,ID,-8.1181,111.8935,76.37,89,90,2.33,overcast clouds
665,665,Ilhabela,BR,-23.7781,-45.3581,79.05,85,86,8.59,overcast clouds
667,667,Mananjary,MG,-21.2167,48.3333,75.92,92,100,11.81,moderate rain

In [19]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Santa Luzia,BR,77.90,light rain,-19.7697,-43.8514,
2,Bosaso,SO,75.63,clear sky,11.2842,49.1816,
6,Butaritari,KI,80.02,moderate rain,3.0707,172.7902,
7,Cidreira,BR,81.23,few clouds,-30.1811,-50.2056,
10,Karratha,AU,82.51,overcast clouds,-20.7377,116.8463,
20,Vila Velha,BR,77.95,broken clouds,-20.3297,-40.2925,
26,Carnarvon,AU,79.25,clear sky,-24.8667,113.6333,
28,Pitimbu,BR,84.79,overcast clouds,-7.4706,-34.8086,
31,Sao Joao Da Barra,BR,80.69,overcast clouds,-21.6403,-41.0511,
36,San Isidro,PE,76.59,clear sky,-12.1167,-77.0500,

In [22]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get the latitude and longitude from the DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping")

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [28]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Santa Luzia,BR,77.90,light rain,-19.7697,-43.8514,Pousada Chao Earth
2,Bosaso,SO,75.63,clear sky,11.2842,49.1816,Red Sea Hotel
6,Butaritari,KI,80.02,moderate rain,3.0707,172.7902,Isles Sunset Lodge
7,Cidreira,BR,81.23,few clouds,-30.1811,-50.2056,Hotel Castelo
10,Karratha,AU,82.51,overcast clouds,-20.7377,116.8463,ibis Styles Karratha
...,...,...,...,...,...,...,...
653,Amarante Do Maranhao,BR,85.93,overcast clouds,-5.5667,-46.7422,Hotéis Caçulinha
654,Araguaina,BR,83.61,broken clouds,-7.1911,-48.2072,Hotel São Vicente
658,Boyolangu,ID,76.37,overcast clouds,-8.1181,111.8935,Yos ega cv
665,Ilhabela,BR,79.05,overcast clouds,-23.7781,-45.3581,Ilha Flat Hotel
667,Mananjary,MG,75.92,moderate rain,-21.2167,48.3333,Vahiny Lodge

In [30]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [31]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [32]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))